### ISSUE TITLE
Find good highlights to showcase

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#286]

**Comment by soi** [comment]
![Screenshot from 2020-02-04 16-04-53](https://user-images.githubusercontent.com/111278/73756901-9d553780-4768-11ea-9de0-a418882abe4e.png)
![Screenshot from 2020-02-04 15-48-04](https://user-images.githubusercontent.com/111278/73756902-9d553780-4768-11ea-93db-b50227f6584e.png)

**Comment by alisandra** [comment]
looks like the RNAseq agrees decidedly better with the reference here... might be a good one to look at to understand why the network might confidently hallucinate a gene all the same
![image](https://user-images.githubusercontent.com/11819588/74349390-7c1dc800-4db4-11ea-8aea-9d05a6fb0698.png)
