### ISSUE TITLE
Somtimes predicted categories don't sum to one (overlap + ensembled)

### ISSUE THREAD

**Issue by alisandra** [weberlab-hhu/GeenuFF#381]
For instance papio_anubis, chunk 479
```
p = h5py.file('predictions.h5') 
i = 479
plt.plot(np.sum(p['predictions'][i], axis=1))
```
![image](https://user-images.githubusercontent.com/11819588/81834525-546c0680-9541-11ea-827c-d23b811db236.png)

maybe an overlapping bug? doesn't change argmax at least

**Comment by soi** [comment]
I believe this is due to the way overlapping is done. Could this chunk be the last one in a chromosome? I vaguely remember that such things happened, but that it also had no effect on the argmax outcome (hopefully)

**Comment by alisandra** [comment]
moved to Helixer repo
