### ISSUE TITLE
Include all data by default in data sets

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#384]
Necessary for augmentation and would make many things easier (would make --keep-errors obsolete). There also should be a /data/fully_errorneous_seqs array being added to remove those on the fly during training.

**Comment by alisandra** [comment]
I had thought this was done and I'm finally merging it in now (also made a lot of the evaluation vs Augustus and RNAseq easier, as well as keeping memory usage under control). But that said final testing shows that there still seems to be a bug on not including unannotated sequences... ultimately kinda important for predicting.

**Comment by alisandra** [comment]
merged into main branch now
