### ISSUE TITLE
Merge Multiple GFFs into one Sqlite3 file

### ISSUE THREAD

**Issue by wyim-pgl** [weberlab-hhu/GeenuFF#394]
Hi,
We are trying to train multiple reference genome for Helixer. We couldn't find any way to merge multiple GFFs into one sqlite3. Do you have any recommendations for it?
Thanks.

**Comment by alisandra** [comment]
Having multiple species in one sqlite3 is no longer necessary nor supported, see recommendations here https://github.com/weberlab-hhu/Helixer/issues/81#issuecomment-1113063616
