### ISSUE TITLE
How to deal with exons that don't align with mRNA entry?

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#40]
e.g. Dusal.0103s00026.v1.0, Dsalina

**Comment by soi** [comment]
They seem to come up quite often (e.g. HORVU5Hr1G059820.1.r1 in Hvulgare), should we maybe interpret that as another way to encode UTRs?

**Comment by alisandra** [comment]
Looks like these two examples are just miss-sorted exons, closing for now
