### ISSUE TITLE
unrecognized feature type from gff: ncRNA_gene

### ISSUE THREAD

**Issue by soi** [weberlab-hhu/GeenuFF#5]
Came up when trying the chromosome downloaded from the source below:

ftp://ftp.ensemblgenomes.org/pub/plants/release-43/fasta/solanum_lycopersicum/dna/Solanum_lycopersicum.SL3.0.dna_rm.chromosome.10.fa.gz

ftp://ftp.ensemblgenomes.org/pub/plants/release-43/gff3/solanum_lycopersicum/Solanum_lycopersicum.SL3.0.43.chromosome.10.gff3.gz

Traceback (most recent call last): 
 File "import_genome.py", line 73, in <module>
    main(args)
  File "import_genome.py", line 55, in main
    importer.add_gff(paths.gff_in)
  File "/home/felix/git/GeenuFF/geenuff/applications/gffimporter.py", line 175, in add_gff
    for entry_group in self.group_gff_by_gene(gff_file):
  File "/home/felix/git/GeenuFF/geenuff/applications/gffimporter.py", line 146, in group_gff_by_gene
    for entry in reader:
  File "/home/felix/git/GeenuFF/geenuff/applications/gffimporter.py", line 138, in useful_gff_entries
    for entry in reader:
  File "/home/felix/git/GeenuFF/geenuff/applications/gffimporter.py", line 105, in gff_gen
    raise ValueError("unrecognized feature type from gff: {}".format(entry.type))
ValueError: unrecognized feature type from gff: ncRNA_gene

**Comment by alisandra** [comment]
Yeah, sorry, currently only a fairly common subset of gff3 types are implemented. In due time we could/should look at getting all the types from here: http://www.sequenceontology.org/

**Comment by alisandra** [comment]
On a similar topic: in the event the gff actually contains some features to take some of the implicit info storage out (e.g. transcription_end_site, transcription_start_site from Augustus), we could use these to check / validate on import, or at least not throw the "ValueError: unrecognized feature type from gff:" error

**Comment by alisandra** [comment]
more specifically Augustus output includes: transcription_end_site, transcription_start_site, stop_codon, start_codon, intron

**Comment by soi** [comment]
we can just add new unknown gff entries to the ignore list
