### ISSUE TITLE
Track or control coordinate & range in h5 file

### ISSUE THREAD

**Issue by alisandra** [weberlab-hhu/GeenuFF#69]
Either add one more datasets with the meta info for each chunk, or alternatively, allow export of specific coordinate(s) & range(s) to h5 file. Basically want to be able to compare existing data & preds (from NNs or Augustus, or other) at specific genomic loci & know what matches up with what.

**Comment by soi** [comment]
The most straight forward way for this I can think of is adding two more arrays to the data: one string array with the seqid + strand of each sequence (a lot of redundancy but should not matter much) and one with the number of actually valid bases in each sequence (excluding the 0-padding). 

With that it should always be reconstructable where exactly the sequence is coming from (if the dataset has been constructed with --only-test-set). We could then also display the seqid + position in the visualization.

Things only could get tricky on the minus strand, not sure about how the numerifier handles that exactly.
